spring.application.name=groupf-notification-service

server.port=${SERVER_PORT:3003}

spring.rabbitmq.host=${RABBITMQ_HOST:host.docker.internal}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:groupf}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:groupf}

rabbitmq.exchange.order=${ORDER_EXCHANGE:order.exchange}
rabbitmq.queue.notification-order=${NOTIFICATION_ORDER_QUEUE:notification.order.queue}
rabbitmq.routing-key.order-created=${ORDER_CREATED_ROUTING_KEY:order.created}